# For developers only:
#  Remove the ece2cmor environment:
#   conda deactivate
#   rm -rf ${mambapath}/envs/ece2cmor3-python-2
#  Create the ece2cmor3 environment:
#    activatemamba
#    mamba update -y --name base mamba           # For updating mamba itself
#    mamba env create -f environment-with-mamba-for-python3.yml
#  Basic tests:
#   which python                                 # ${mambapath}/envs/ece2cmor3-python-3/bin/python
#   python --version                             # Python 3.11.1
#   cdo -V                                       # version 1.9.6
#   drq -v                                       # version 01.02.00
#   drq -h
#   ece2cmor -V                                  # ece2cmor v1.8.1
#  Investigate the effect of another drq version (run this when your ece2cmor3 environment is active):
#   pip uninstall -y dreqPy==01.2.0; pip install dreqPy==01.0.33
#  This dreq version stays (also in next sessions) as long the ece2cmor environment is not recreated.

name: ece2cmor3-python-3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cdo=1.9.6
  - cmor=3.5.0
  - dreqPy==01.2.0
  - f90nml
  - gitpython
  - jsonschema
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyngl
  - pytest
  - python
  - python-cdo
  - python-eccodes
  - python-dateutil
  - requests
  - testfixtures
  - xarray
  - xlsxwriter
  # Additionally required by tem-diag:
  - nco
  - scipy
