package:
  name: ece2cmor3
  version: 1.0.0

source:
  git_rev: v1.0.0
  git_url: https://github.com/EC-Earth/ece2cmor3.git

build:
  number: 0
  string: np112py27_0

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - python-dateutil >=2.6.0
    - numpy 1.12.1
    - cdo >=1.8.2
    - python-cdo >=1.3.3
    - cmor 3.2.3 # some tests fail with 3.2.4
    - f90nml >=0.20
    - netcdf4 >=1.2.7

test:
  source_files:
    - test
  imports:
    - ece2cmor3
  requires:
    - testfixtures >=4.10.0
    - nose >=1.3.7
  commands:
    nosetests -v

about:
  home: https://github.com/EC-Earth/ece2cmor3
  license: "Apache License, Version 2.0"
  license_file: LICENSE
