name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Mamba install
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ece2cmor3
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        miniforge-version: "latest"
        miniforge-variant: Mambaforge
        use-mamba: true
        auto-update-conda: true
       #auto-activate-base: false
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate ece2cmor3
        mamba install pytest
        pip install -e .
        pytest --verbose
#   - name: Lint with flake8
#     shell: bash -l {0}
#     run: |
#       mamba install flake8
#       # stop the build if there are Python syntax errors or undefined names
#       python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#       python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
